# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Spring Configuration
spring:

  #to enable colors when you run your app outside intellij

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/OpinionHub?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
  liquibase:
    enabled: false
    change-log: db/master.xml

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

application:
  security:
    jwt:
      secret-key: 586B633834416E396D7436753879382F423F4428482B4C6250655367566B5970
      expiration:  3600000 #  15 min in ms
      cookie-name: jwt-cookie

upload:
  folder: ./src/main/resources/uploads






